# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BetterProfessorApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterProfessorApp
pod 'SwiftLint'

  target 'BetterProfessorAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterProfessorAppUITests' do
    # Pods for testing
  end

end
